# Generated by Django 5.1.6 on 2025-10-10 02:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_jobdriverassignment_job_driver_truck_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('fuel_program', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fuel_pilot_or_kt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fuel_surcharge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_weight_or_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_truck_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_reports', to='myapp.driver')),
            ],
            options={
                'ordering': ['-week_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayReportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('job_number', models.CharField(max_length=255)),
                ('truck_number', models.CharField(max_length=100)),
                ('trailer_number', models.CharField(blank=True, max_length=100)),
                ('loaded', models.CharField(blank=True, max_length=255)),
                ('unloaded', models.CharField(blank=True, max_length=255)),
                ('weight_or_hour', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('truck_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('trailer_rent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('broker_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('contractor_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_report_lines', to='myapp.job')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='myapp.payreport')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='payreport',
            index=models.Index(fields=['driver', 'week_start', 'week_end'], name='myapp_payre_driver__4c180f_idx'),
        ),
        migrations.AddIndex(
            model_name='payreport',
            index=models.Index(fields=['week_start'], name='myapp_payre_week_st_b60f18_idx'),
        ),
        migrations.AddIndex(
            model_name='payreport',
            index=models.Index(fields=['week_end'], name='myapp_payre_week_en_ed3321_idx'),
        ),
        migrations.AddConstraint(
            model_name='payreport',
            constraint=models.CheckConstraint(condition=models.Q(('week_start__lte', models.F('week_end'))), name='pr_week_start_lte_end'),
        ),
        migrations.AddConstraint(
            model_name='payreport',
            constraint=models.UniqueConstraint(fields=('driver', 'week_start', 'week_end'), name='uniq_payreport_driver_week'),
        ),
        migrations.AddIndex(
            model_name='payreportline',
            index=models.Index(fields=['report', 'date'], name='myapp_payre_report__367a71_idx'),
        ),
        migrations.AddIndex(
            model_name='payreportline',
            index=models.Index(fields=['job_number'], name='myapp_payre_job_num_ec6ee4_idx'),
        ),
    ]
